# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
mode: sequential
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "push"

steps:
  clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: 'clone'

  Freestyle:
    title: Running docker image
    type: freestyle
    working_directory: '${{clone}}'
    arguments:
      image: 'alpine'
      commands:
        - echo "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
        - ls -ltr
        - echo $(pwd)

  build:
    title: "Building Docker image"
    type: "build"
    working_directory: '${{clone}}'
    arguments:
      image_name: 'safficodefresh/${{CF_REPO_NAME}}'
      tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    # Set 'latest' tag on the image. Or, use built-in variables
    # like ${{CF_BRANCH_TAG_NORMALIZED}} to use the current branch name/tag.
    dockerfile: "Dockerfile"
    stage: "build"

  push_to_my_registry:
    stage: 'push'
    type: push
    title: Pushing to a registry ${{CF_BRANCH_TAG_NORMALIZED}}
    candidate: ${{build}}
    registry: dockerhub
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}

